Repository hcsp/create-an-empty-class-in-package, pull requests merged in 2019-10, with the labels that each got.

#104 creat package class
  src/main/java/my/cute/Cat.java
Labels: is:answer

#105 new package and new classs called Cat
  src/main/java/my/cute/Cat.java
Labels: is:answer

#106 在指定包中创建了一个Cat类
  src/main/java/my/cute/Cat.java
Labels: from:VIP, is:answer

#107 在my.cute包中创建了一个名为Cat的公开类
  src/main/java/my/cute/Cat.java
Labels: is:answer

#108 add: 在my.cute包中（即src/main/java/my/cute目录中）创建了一个名为Cat的公开类
  src/main/java/my/cute/Cat.java
Labels: is:answer

#110 create a Cat class in package ```my.cute```
  src/main/java/my/cute/Cat.java
Labels: from:VIP, is:answer

#111 在指定包中创建了Cat类
  src/main/java/my/cute/Cat.java
Labels: from:VIP, is:answer

#112 每个类都包含在一个包内，包的名字由类所在的目录决定。
  src/main/java/my/cute/Cat.java
Labels: is:answer

#113 在指定包下面创建一个类，类的全限定名由类所在的包名（或者目录）确定。
  src/main/java/my/cute/Cat.java
Labels: from:VIP, is:answer

#114 在src/main/java/my/cute中创建了了Cat公开类
  src/main/java/my/cute/Cat.java
Labels: from:VIP, is:answer

#115 在指定包中创建一个Cat类
  src/main/java/my/cute/Cat.java
Labels: from:VIP, is:answer

#116 Update .gitignore
  .gitignore
Labels: enhancement, is:enhancement

#117 创建类
  src/main/java/my/cute/Cat.java
Labels: is:answer

#119 submit again
  src/main/java/my/cute/Cat.java
Labels: is:answer

#120 在my.cute下创建Cat类
  src/main/java/my/cute/Cat.java
Labels: is:answer

#121 创建一个名为Cat的公开类
  src/main/java/my/cute/Cat.java
Labels: is:answer

#122 创建my.cute包，增加Cat类
  src/main/java/my/cute/Cat.java
Labels: from:VIP, is:answer

#124 在包中创建一个类
  src/main/java/my/cute/Cat.java
Labels: is:answer

#125 包中创建类
  src/main/java/my/cute/Cat.java
Labels: is:answer

#126 在 my.cute 包中新建 Cat 类
  src/main/java/my/cute/Cat.java
Labels: from:VIP, is:answer
